### ISSUE TITLE
Anyone interested in a hard fork?

### ISSUE THREAD

**Issue by wiseaidev** [redis/redis-om-python#338]
Hey everyone. Since this project is not actively maintained anymore, the [last release](https://github.com/redis/redis-om-python/tree/v0.0.27) was around 3 months ago, and I am thinking to release a new package/version based on a fork I am currently working on that includes all the patches, additional features, docs... Is anyone interested? Is it ok @simonprickett @ everyone to do so? How about licensing? Do i need to release it under the MIT license?

**Comment by simonprickett** [comment]
This project has been moving to the Redis (the company) client team and is maintained by @dvora-h and @chayim

**Comment by chayim** [comment]
Hi folks - maintenance is on. There have been some small changes to the release process. We're in the process of adding features like bulk delete, and aggregations as we speak. 

Part of the explicit reason for the delay is that we've brought on a PM (@thomascaudron) and asked him to help prioritize things so that we work on the right things - this is especially true as GitHub issues doesn't reflect a complete list of asks.

I'd ask that we maintain any and all feedback we have for *all* OM clients in these issues, so that @thomascaudron can help us out!

**Comment by wiseaidev** [comment]
Hey @chayim, sounds great. So, could you please review my PRs, especially the one @ [pull/337](https://github.com/redis/redis-om-python/pull/337) cause it prevents us to create a model with a field named `id`.

**Comment by wiseaidev** [comment]
Closing this issue because it is still an active project. At first, i thought it was abandoned! Ma bad! Anyways, hoping to see a new release soon.

**Comment by chayim** [comment]
@wiseaidev I'll try and look today.  Saw the six comment previously and immediately :heart:  Baby steps my friend!
