### ISSUE TITLE
how can I search by condition

### ISSUE THREAD

**Issue by saifullah-repliq** [redis/redis-om-python#579]
```
results = []
 
if name:
  results = BaseProductPy.find(BaseProductPy.name % f"{name}*")
 
if tags:
  results = results.find(BaseProductPy.tag.value == tags)
 
if city:
  results = results.find(BaseProductPy.address.city == city)
 
return results

```

how can i search by condition where if name is there, find by name. if tag is there, find by name and tag. If city is there, find by name, tag and city.

how can i do that?

**Comment by slorello89** [comment]
If you're ok with OR semantics then you can just or the predicates together. Otherwise there really isn't a good way in Redis OM Python at the moment of conditionally searching fields (you can do it via [aggregations](https://redis.io/docs/interact/search-and-query/advanced-concepts/aggregations/#filter-expressions) using redis-py.

**Comment by slorello89** [comment]
Or you could of course just pull back the OR case and filter it down further in your app
